model:
  encoder:
    channels: 128
    in_channels: 3
    out_channels: 3
    channel_multipliers: [1,2,4,4]  # num_down = len(ch_mult)-1
    num_resnet_blocks: 2
    dropout: 0.0
    resolution: 256
    z_channels: 4
    double_z: True

  decoder:
    channels: 128
    in_channels: 3
    out_channels: 3
    channel_multipliers: [1,2,4,4]  # num_down = len(ch_mult)-1
    num_resnet_blocks: 2
    dropout: 0.0
    resolution: 256
    z_channels: 4
    double_z: True

  auto_encoder:
    emb_channels: 4
    z_channels: 4
    use_BN: True
  
  loss:
    logvar_init: 0.0
    kl_weight: 1e-6
    perceptual_weight: 1.0

training:
  use_cuda: [0, 1]
  image_size: 256
  batch_size: 8
  epochs: 10
  learning_rate: 4.5e-6
  weight_decay: 4.5e-6
  model_path: './checkpoint/MS_COCO_VAE3.pkl'
  load_model: false